### ISSUE TITLE
liri pulse module does not compile with Qt 5.14

### ISSUE THREAD

**Issue by n3rdopolis** [lirios/pulseaudio#4]
I seem to be unable to compile this module with Qt 5.14 . I get this below error, even when trying the (seemingly?) obvious attempt of adding a `#include <QMapIterator>` to `src/imports/pulseaudio/qpulseaudio/maps.cpp`

```
[ 71%] Building CXX object src/imports/pulseaudio/CMakeFiles/pulseaudioplugin.dir/qpulseaudio/pulseobject.cpp.o
In file included from /srcbuild/lirios-pulseaudio/src/imports/pulseaudio/qpulseaudio/maps.cpp:21:
/srcbuild/lirios-pulseaudio/src/imports/pulseaudio/qpulseaudio/maps.h: In member function ‘int QPulseAudio::MapBase<Type, PAInfo>::indexOfObject(QObject*) const’:
/srcbuild/lirios-pulseaudio/src/imports/pulseaudio/qpulseaudio/maps.h:85:9: error: ‘QMapIterator’ was not declared in this scope
         QMapIterator<quint32, Type *> it(m_data);
         ^~~~~~~~~~~~
/srcbuild/lirios-pulseaudio/src/imports/pulseaudio/qpulseaudio/maps.h:85:9: note: suggested alternative: ‘operator=’
         QMapIterator<quint32, Type *> it(m_data);
         ^~~~~~~~~~~~
         operator=

```

**Comment by n3rdopolis** [comment]
Got it to build by commenting out `QT_NO_JAVA_STYLE_ITERATORS` in `https://github.com/lirios/cmake-shared/blob/develop/modules/LiriAddQmlPlugin.cmake`

**Comment by plfiorini** [comment]
Fixed
